git actions

diff --git a/.github/workflows/example07.yml b/.github/workflows/example07.yml
--- a/.github/workflows/example07.yml
+++ b/.github/workflows/example07.yml
@@ -6,4 +6,7 @@ jobs:
         steps:
             - run: |
                 echo "::error Intentional Error::missing semicolon" 
-                exit 1
+                # exit 1
+       steps: 
+            - run: |
+                echo "::summary 100 resources created ::Missing semicolon"
